// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  | FaqWithCtaSlice
  | ProjectHeroSlice
  | RoadmapSlice
  | AboutSlice
  | ServicesSlice
  | HeroSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Item in *About → Default → Primary → photos*
 */
export interface AboutSliceDefaultPrimaryPhotosItem {
  /**
   * city field in *About → Default → Primary → photos*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.photos[].city
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  city: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Title field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * background video field in *About → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * photos field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.photos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  photos: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryPhotosItem>>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *AboutWithImagesGrid → Default → Primary → Cards*
 */
export interface AboutWithImagesGridSliceDefaultPrimaryCardsItem {
  /**
   * Media field in *AboutWithImagesGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.cards[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *AboutWithImagesGrid → Default → Primary*
 */
export interface AboutWithImagesGridSliceDefaultPrimary {
  /**
   * Heading field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * subtitle field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Cards field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<AboutWithImagesGridSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for AboutWithImagesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading, a text description, and a grid of repeatable image cards.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutWithImagesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutWithImagesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutWithImagesGrid*
 */
type AboutWithImagesGridSliceVariation = AboutWithImagesGridSliceDefault;

/**
 * AboutWithImagesGrid Shared Slice
 *
 * - **API ID**: `about_with_images_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutWithImagesGridSlice = prismic.SharedSlice<
  "about_with_images_grid",
  AboutWithImagesGridSliceVariation
>;

/**
 * Item in *FaqWithCta → Default → Primary → FAQs*
 */
export interface FaqWithCtaSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *FaqWithCta → Default → Primary → FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqWithCta → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqWithCta → Default → Primary*
 */
export interface FaqWithCtaSliceDefaultPrimary {
  /**
   * Section Subtitle field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * FAQs field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaqWithCtaSliceDefaultPrimaryFaqsItem>>;

  /**
   * CTA Media field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  cta_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * CTA Title field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField;

  /**
   * CTA Description field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField;

  /**
   * CTA Button field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Section title field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Default variation for FaqWithCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard variation with FAQ group and contact CTA card.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqWithCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqWithCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqWithCta*
 */
type FaqWithCtaSliceVariation = FaqWithCtaSliceDefault;

/**
 * FaqWithCta Shared Slice
 *
 * - **API ID**: `faq_with_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqWithCtaSlice = prismic.SharedSlice<
  "faq_with_cta",
  FaqWithCtaSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Title action*
 */
export interface HeroSliceDefaultPrimaryTitleActionItem {
  /**
   * action field in *Hero → Default → Primary → Title action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_action[].action
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  action: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Call to action field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://bayvine.digital
   * - **API ID Path**: hero.default.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  call_to_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Call to action label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SCHEDULE YOUR FREE INTRO
   * - **API ID Path**: hero.default.primary.call_to_action_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action_label: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Web and App development  •  E-Commerce  •  Web and UX/UI Design
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title action field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_action[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  title_action: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryTitleActionItem>
  >;

  /**
   * banner field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.banner
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  banner: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ProjectHero → Default → Primary → Project Tags*
 */
export interface ProjectHeroSliceDefaultPrimaryProjectTagsItem {
  /**
   * Tag field in *ProjectHero → Default → Primary → Project Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectHero → Default → Primary*
 */
export interface ProjectHeroSliceDefaultPrimary {
  /**
   * Project Title field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_title: prismic.RichTextField;

  /**
   * Project Subtitle field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_subtitle: prismic.RichTextField;

  /**
   * Project Tags field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project_tags: prismic.GroupField<
    Simplify<ProjectHeroSliceDefaultPrimaryProjectTagsItem>
  >;

  /**
   * Project Description field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * Mockup Image field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.mockup_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mockup_image: prismic.ImageField<never>;

  /**
   * Mockup device field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.mockup_device
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mockup_device: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero layout with prominent left-aligned content and right visual mockup.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectHero*
 */
type ProjectHeroSliceVariation = ProjectHeroSliceDefault;

/**
 * ProjectHero Shared Slice
 *
 * - **API ID**: `project_hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectHeroSlice = prismic.SharedSlice<
  "project_hero",
  ProjectHeroSliceVariation
>;

/**
 * Item in *Roadmap → Default → Primary → roadmap*
 */
export interface RoadmapSliceDefaultPrimaryRoadmapItem {
  /**
   * title field in *Roadmap → Default → Primary → roadmap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Roadmap → Default → Primary → roadmap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * media field in *Roadmap → Default → Primary → roadmap*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *Roadmap → Default → Primary*
 */
export interface RoadmapSliceDefaultPrimary {
  /**
   * Title field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitel field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.subtitel
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitel: prismic.RichTextField;

  /**
   * roadmap field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  roadmap: prismic.GroupField<Simplify<RoadmapSliceDefaultPrimaryRoadmapItem>>;

  /**
   * background cta field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.background_cta
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_cta: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * cta link field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * cta label field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * cta title field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField;
}

/**
 * Default variation for Roadmap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoadmapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoadmapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Roadmap*
 */
type RoadmapSliceVariation = RoadmapSliceDefault;

/**
 * Roadmap Shared Slice
 *
 * - **API ID**: `roadmap`
 * - **Description**: Roadmap
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoadmapSlice = prismic.SharedSlice<
  "roadmap",
  RoadmapSliceVariation
>;

/**
 * Item in *Services → Default → Primary → Services*
 */
export interface ServicesSliceDefaultPrimaryServicesItem {
  /**
   * Hover image field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].hover_image
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  hover_image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Service description field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  service_description: prismic.RichTextField;

  /**
   * Link field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Services field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<
    Simplify<ServicesSliceDefaultPrimaryServicesItem>
  >;

  /**
   * Title field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryPhotosItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AboutWithImagesGridSlice,
      AboutWithImagesGridSliceDefaultPrimaryCardsItem,
      AboutWithImagesGridSliceDefaultPrimary,
      AboutWithImagesGridSliceVariation,
      AboutWithImagesGridSliceDefault,
      FaqWithCtaSlice,
      FaqWithCtaSliceDefaultPrimaryFaqsItem,
      FaqWithCtaSliceDefaultPrimary,
      FaqWithCtaSliceVariation,
      FaqWithCtaSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryTitleActionItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProjectHeroSlice,
      ProjectHeroSliceDefaultPrimaryProjectTagsItem,
      ProjectHeroSliceDefaultPrimary,
      ProjectHeroSliceVariation,
      ProjectHeroSliceDefault,
      RoadmapSlice,
      RoadmapSliceDefaultPrimaryRoadmapItem,
      RoadmapSliceDefaultPrimary,
      RoadmapSliceVariation,
      RoadmapSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryServicesItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
    };
  }
}
