// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ContactDocumentDataSlicesSlice =
  | FooterCtaNavigationBrandingSlice
  | ContactFormSlice;

/**
 * Content for contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Privacy policy field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.privacy_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  privacy_policy: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Trademark field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.trademark
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  trademark: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | FooterCtaNavigationBrandingSlice
  | AboutWithImagesGridSlice
  | FaqWithCtaSlice
  | ProjectHeroSlice
  | RoadmapSlice
  | AboutSlice
  | ServicesSlice
  | HeroSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ProjectDocumentDataSlicesSlice =
  | ProjectDetailHeroSlice
  | ProjectTitleParagraphSlice
  | ProjectStatsSlice
  | ProjectCtaSlice
  | ProjectTestimonialSlice
  | ProjectMediaGridSlice
  | ProjectSingleMediaSlice
  | ProjectDoubleColumnTextSlice
  | FooterCtaNavigationBrandingSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

type ServiceDocumentDataSlicesSlice =
  | ProjectDetailHeroSlice
  | ProjectTitleParagraphSlice
  | ProjectStatsSlice
  | ProjectCtaSlice
  | ServiceHeroSlice
  | ServiceFitSlice
  | ServiceProcessSlice
  | ServiceHighlightSlice
  | RelatedProjectSlice
  | FaqWithCtaSlice
  | ProjectTestimonialSlice
  | ProjectMediaGridSlice
  | ProjectSingleMediaSlice
  | ProjectDoubleColumnTextSlice
  | FooterCtaNavigationBrandingSlice;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes =
  | ContactDocument
  | FooterDocument
  | HomeDocument
  | ProjectDocument
  | ServiceDocument;

/**
 * Item in *About → Default → Primary → photos*
 */
export interface AboutSliceDefaultPrimaryPhotosItem {
  /**
   * city field in *About → Default → Primary → photos*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.photos[].city
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  city: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Title field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * background video field in *About → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * photos field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.photos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  photos: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryPhotosItem>>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *AboutWithImagesGrid → Default → Primary → Cards*
 */
export interface AboutWithImagesGridSliceDefaultPrimaryCardsItem {
  /**
   * Media field in *AboutWithImagesGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.cards[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *AboutWithImagesGrid → Default → Primary*
 */
export interface AboutWithImagesGridSliceDefaultPrimary {
  /**
   * Heading field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * subtitle field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Cards field in *AboutWithImagesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_with_images_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<AboutWithImagesGridSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for AboutWithImagesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading, a text description, and a grid of repeatable image cards.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutWithImagesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutWithImagesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutWithImagesGrid*
 */
type AboutWithImagesGridSliceVariation = AboutWithImagesGridSliceDefault;

/**
 * AboutWithImagesGrid Shared Slice
 *
 * - **API ID**: `about_with_images_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutWithImagesGridSlice = prismic.SharedSlice<
  "about_with_images_grid",
  AboutWithImagesGridSliceVariation
>;

/**
 * Item in *ContactForm → Default → Primary → Contact Options*
 */
export interface ContactFormSliceDefaultPrimaryContactOptionsItem {
  /**
   * Label field in *ContactForm → Default → Primary → Contact Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.contact_options[].option_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  option_label: prismic.KeyTextField;

  /**
   * Link or action (email, phone, calendar) field in *ContactForm → Default → Primary → Contact Options*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.contact_options[].option_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  option_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *ContactForm → Default → Primary → Interest Services*
 */
export interface ContactFormSliceDefaultPrimaryInterestServicesItem {
  /**
   * Service field in *ContactForm → Default → Primary → Interest Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.interest_services[].service
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service: prismic.KeyTextField;
}

/**
 * Item in *ContactForm → Default → Primary → Budget Options*
 */
export interface ContactFormSliceDefaultPrimaryBudgetOptionsItem {
  /**
   * Budget Option field in *ContactForm → Default → Primary → Budget Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.budget_options[].budget_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  budget_label: prismic.KeyTextField;
}

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Heading field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheading: prismic.RichTextField;

  /**
   * 'Got questions?' Link field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.questions_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  questions_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Contact Options field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.contact_options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_options: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryContactOptionsItem>
  >;

  /**
   * Interest Services field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.interest_services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  interest_services: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryInterestServicesItem>
  >;

  /**
   * Name Label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_label: prismic.KeyTextField;

  /**
   * Email Label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField;

  /**
   * Phone Label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.phone_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_label: prismic.KeyTextField;

  /**
   * Budget Options field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.budget_options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  budget_options: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryBudgetOptionsItem>
  >;

  /**
   * Project Description Label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.about_project_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_project_label: prismic.KeyTextField;

  /**
   * Project Description Placeholder field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.about_project_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_project_placeholder: prismic.KeyTextField;

  /**
   * Button Label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.submit_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_label: prismic.KeyTextField;

  /**
   * Disclaimer field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  disclaimer: prismic.RichTextField;

  /**
   * Hero background field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.hero_background
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  hero_background: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard contact and inquiry form with service selection and direct contact options.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *FaqWithCta → Default → Primary → FAQs*
 */
export interface FaqWithCtaSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *FaqWithCta → Default → Primary → FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqWithCta → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqWithCta → Default → Primary*
 */
export interface FaqWithCtaSliceDefaultPrimary {
  /**
   * Section Subtitle field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * FAQs field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaqWithCtaSliceDefaultPrimaryFaqsItem>>;

  /**
   * CTA Media field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  cta_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * CTA Title field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField;

  /**
   * CTA Description field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField;

  /**
   * CTA Button field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Section title field in *FaqWithCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_cta.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Default variation for FaqWithCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard variation with FAQ group and contact CTA card.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqWithCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqWithCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqWithCta*
 */
type FaqWithCtaSliceVariation = FaqWithCtaSliceDefault;

/**
 * FaqWithCta Shared Slice
 *
 * - **API ID**: `faq_with_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqWithCtaSlice = prismic.SharedSlice<
  "faq_with_cta",
  FaqWithCtaSliceVariation
>;

/**
 * Item in *FooterCtaNavigationBranding → Default → Primary → nav groups*
 */
export interface FooterCtaNavigationBrandingSliceDefaultPrimaryPageNavLinksItem {
  /**
   * heading field in *FooterCtaNavigationBranding → Default → Primary → nav groups*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.page_nav_links[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * nav item field in *FooterCtaNavigationBranding → Default → Primary → nav groups*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.page_nav_links[].nav_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_item: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *FooterCtaNavigationBranding → Default → Primary*
 */
export interface FooterCtaNavigationBrandingSliceDefaultPrimary {
  /**
   * CTA Heading field in *FooterCtaNavigationBranding → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.cta_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_heading: prismic.KeyTextField;

  /**
   * CTA Text field in *FooterCtaNavigationBranding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_text: prismic.RichTextField;

  /**
   * CTA Button field in *FooterCtaNavigationBranding → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * nav groups field in *FooterCtaNavigationBranding → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.page_nav_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  page_nav_links: prismic.GroupField<
    Simplify<FooterCtaNavigationBrandingSliceDefaultPrimaryPageNavLinksItem>
  >;

  /**
   * Motto field in *FooterCtaNavigationBranding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.motto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  motto: prismic.RichTextField;

  /**
   * Branding field in *FooterCtaNavigationBranding → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_cta_navigation_branding.default.primary.branding
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  branding: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for FooterCtaNavigationBranding Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard footer layout with call-to-action, grouped navigational links, secondary legal links, brand logo/text, and optional motto.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterCtaNavigationBrandingSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<FooterCtaNavigationBrandingSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *FooterCtaNavigationBranding*
 */
type FooterCtaNavigationBrandingSliceVariation =
  FooterCtaNavigationBrandingSliceDefault;

/**
 * FooterCtaNavigationBranding Shared Slice
 *
 * - **API ID**: `footer_cta_navigation_branding`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterCtaNavigationBrandingSlice = prismic.SharedSlice<
  "footer_cta_navigation_branding",
  FooterCtaNavigationBrandingSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Title action*
 */
export interface HeroSliceDefaultPrimaryTitleActionItem {
  /**
   * action field in *Hero → Default → Primary → Title action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_action[].action
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  action: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Call to action field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://bayvine.digital
   * - **API ID Path**: hero.default.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  call_to_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Call to action label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SCHEDULE YOUR FREE INTRO
   * - **API ID Path**: hero.default.primary.call_to_action_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action_label: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Web and App development  •  E-Commerce  •  Web and UX/UI Design
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title action field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_action[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  title_action: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryTitleActionItem>
  >;

  /**
   * banner field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.banner
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  banner: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProjectCTA → Default → Primary*
 */
export interface ProjectCtaSliceDefaultPrimary {
  /**
   * Heading field in *ProjectCTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *ProjectCTA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cta.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Primary CTA Label field in *ProjectCTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cta.default.primary.primary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_label: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *ProjectCTA → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cta.default.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Label field in *ProjectCTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cta.default.primary.secondary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_label: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *ProjectCTA → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cta.default.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ProjectCTA Slice
 *
 * - **API ID**: `default`
 * - **Description**: CTA block with up to two buttons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectCTA*
 */
type ProjectCtaSliceVariation = ProjectCtaSliceDefault;

/**
 * ProjectCTA Shared Slice
 *
 * - **API ID**: `project_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectCtaSlice = prismic.SharedSlice<
  "project_cta",
  ProjectCtaSliceVariation
>;

/**
 * Item in *ProjectDetailHero → Default → Primary → Tags*
 */
export interface ProjectDetailHeroSliceDefaultPrimaryTagsItem {
  /**
   * Tag field in *ProjectDetailHero → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_detail_hero.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectDetailHero → Default → Primary*
 */
export interface ProjectDetailHeroSliceDefaultPrimary {
  /**
   * Title field in *ProjectDetailHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_detail_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProjectDetailHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_detail_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Tags field in *ProjectDetailHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_detail_hero.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<
    Simplify<ProjectDetailHeroSliceDefaultPrimaryTagsItem>
  >;

  /**
   * Background Image field in *ProjectDetailHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_detail_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Video field in *ProjectDetailHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_detail_hero.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ProjectDetailHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero with background media, title, tags, and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectDetailHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectDetailHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectDetailHero*
 */
type ProjectDetailHeroSliceVariation = ProjectDetailHeroSliceDefault;

/**
 * ProjectDetailHero Shared Slice
 *
 * - **API ID**: `project_detail_hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectDetailHeroSlice = prismic.SharedSlice<
  "project_detail_hero",
  ProjectDetailHeroSliceVariation
>;

/**
 * Item in *ProjectDoubleColumnText → Default → Primary → Details*
 */
export interface ProjectDoubleColumnTextSliceDefaultPrimaryDetailsItem {
  /**
   * Label field in *ProjectDoubleColumnText → Default → Primary → Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_double_column_text.default.primary.details[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *ProjectDoubleColumnText → Default → Primary → Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_double_column_text.default.primary.details[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectDoubleColumnText → Default → Primary*
 */
export interface ProjectDoubleColumnTextSliceDefaultPrimary {
  /**
   * Title field in *ProjectDoubleColumnText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_double_column_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ProjectDoubleColumnText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_double_column_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Details field in *ProjectDoubleColumnText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_double_column_text.default.primary.details[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  details: prismic.GroupField<
    Simplify<ProjectDoubleColumnTextSliceDefaultPrimaryDetailsItem>
  >;
}

/**
 * Default variation for ProjectDoubleColumnText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Two-column text with detail list.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectDoubleColumnTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectDoubleColumnTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectDoubleColumnText*
 */
type ProjectDoubleColumnTextSliceVariation =
  ProjectDoubleColumnTextSliceDefault;

/**
 * ProjectDoubleColumnText Shared Slice
 *
 * - **API ID**: `project_double_column_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectDoubleColumnTextSlice = prismic.SharedSlice<
  "project_double_column_text",
  ProjectDoubleColumnTextSliceVariation
>;

/**
 * Item in *ProjectHero → Default → Primary → Project Tags*
 */
export interface ProjectHeroSliceDefaultPrimaryProjectTagsItem {
  /**
   * Tag field in *ProjectHero → Default → Primary → Project Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectHero → Default → Primary*
 */
export interface ProjectHeroSliceDefaultPrimary {
  /**
   * Project Title field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_title: prismic.RichTextField;

  /**
   * Project Subtitle field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_subtitle: prismic.RichTextField;

  /**
   * Project Tags field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project_tags: prismic.GroupField<
    Simplify<ProjectHeroSliceDefaultPrimaryProjectTagsItem>
  >;

  /**
   * Project Description field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * Project Link field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.project_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project_link: prismic.ContentRelationshipField<"project">;

  /**
   * Mockup Image field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.mockup_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mockup_image: prismic.ImageField<never>;

  /**
   * Background video field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ProjectHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero layout with prominent left-aligned content and right visual mockup.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectHero*
 */
type ProjectHeroSliceVariation = ProjectHeroSliceDefault;

/**
 * ProjectHero Shared Slice
 *
 * - **API ID**: `project_hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectHeroSlice = prismic.SharedSlice<
  "project_hero",
  ProjectHeroSliceVariation
>;

/**
 * Item in *ProjectMediaGrid → Default → Primary → Media Items*
 */
export interface ProjectMediaGridSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *ProjectMediaGrid → Default → Primary → Media Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_media_grid.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *ProjectMediaGrid → Default → Primary → Media Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_media_grid.default.primary.items[].video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Caption field in *ProjectMediaGrid → Default → Primary → Media Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_media_grid.default.primary.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectMediaGrid → Default → Primary*
 */
export interface ProjectMediaGridSliceDefaultPrimary {
  /**
   * Heading field in *ProjectMediaGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_media_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Media Items field in *ProjectMediaGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_media_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ProjectMediaGridSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ProjectMediaGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of images and videos.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectMediaGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectMediaGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectMediaGrid*
 */
type ProjectMediaGridSliceVariation = ProjectMediaGridSliceDefault;

/**
 * ProjectMediaGrid Shared Slice
 *
 * - **API ID**: `project_media_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectMediaGridSlice = prismic.SharedSlice<
  "project_media_grid",
  ProjectMediaGridSliceVariation
>;

/**
 * Primary content in *ProjectSingleMedia → Default → Primary*
 */
export interface ProjectSingleMediaSliceDefaultPrimary {
  /**
   * Image field in *ProjectSingleMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_single_media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *ProjectSingleMedia → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_single_media.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Caption field in *ProjectSingleMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_single_media.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for ProjectSingleMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Full-bleed image or video.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSingleMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSingleMediaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectSingleMedia*
 */
type ProjectSingleMediaSliceVariation = ProjectSingleMediaSliceDefault;

/**
 * ProjectSingleMedia Shared Slice
 *
 * - **API ID**: `project_single_media`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSingleMediaSlice = prismic.SharedSlice<
  "project_single_media",
  ProjectSingleMediaSliceVariation
>;

/**
 * Item in *ProjectStats → Default → Primary → Stats*
 */
export interface ProjectStatsSliceDefaultPrimaryStatsItem {
  /**
   * Icon field in *ProjectStats → Default → Primary → Stats*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_stats.default.primary.stats[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Value field in *ProjectStats → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_stats.default.primary.stats[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * Description field in *ProjectStats → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_stats.default.primary.stats[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectStats → Default → Primary*
 */
export interface ProjectStatsSliceDefaultPrimary {
  /**
   * Heading field in *ProjectStats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_stats.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Stats field in *ProjectStats → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_stats.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<ProjectStatsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for ProjectStats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Stat cards with icon, value, and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectStatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectStatsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectStats*
 */
type ProjectStatsSliceVariation = ProjectStatsSliceDefault;

/**
 * ProjectStats Shared Slice
 *
 * - **API ID**: `project_stats`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectStatsSlice = prismic.SharedSlice<
  "project_stats",
  ProjectStatsSliceVariation
>;

/**
 * Primary content in *ProjectTestimonial → Default → Primary*
 */
export interface ProjectTestimonialSliceDefaultPrimary {
  /**
   * Quote field in *ProjectTestimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Author Name field in *ProjectTestimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_testimonial.default.primary.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Title field in *ProjectTestimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_testimonial.default.primary.author_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_title: prismic.KeyTextField;

  /**
   * Author Company field in *ProjectTestimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_testimonial.default.primary.author_company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_company: prismic.KeyTextField;

  /**
   * Author Image field in *ProjectTestimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_testimonial.default.primary.author_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_image: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectTestimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Client testimonial with quote and author details.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectTestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectTestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectTestimonial*
 */
type ProjectTestimonialSliceVariation = ProjectTestimonialSliceDefault;

/**
 * ProjectTestimonial Shared Slice
 *
 * - **API ID**: `project_testimonial`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectTestimonialSlice = prismic.SharedSlice<
  "project_testimonial",
  ProjectTestimonialSliceVariation
>;

/**
 * Primary content in *ProjectTitleParagraph → Default → Primary*
 */
export interface ProjectTitleParagraphSliceDefaultPrimary {
  /**
   * Title field in *ProjectTitleParagraph → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_title_paragraph.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ProjectTitleParagraph → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_title_paragraph.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for ProjectTitleParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Title with supporting paragraph text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectTitleParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectTitleParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectTitleParagraph*
 */
type ProjectTitleParagraphSliceVariation = ProjectTitleParagraphSliceDefault;

/**
 * ProjectTitleParagraph Shared Slice
 *
 * - **API ID**: `project_title_paragraph`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectTitleParagraphSlice = prismic.SharedSlice<
  "project_title_paragraph",
  ProjectTitleParagraphSliceVariation
>;

/**
 * Item in *RelatedProject → Default → Primary → Project Tags*
 */
export interface RelatedProjectSliceDefaultPrimaryProjectTagsItem {
  /**
   * Tag field in *RelatedProject → Default → Primary → Project Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.project_tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *RelatedProject → Default → Primary*
 */
export interface RelatedProjectSliceDefaultPrimary {
  /**
   * Heading field in *RelatedProject → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Project field in *RelatedProject → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * Project Title field in *RelatedProject → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project Description field in *RelatedProject → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * Project Tags field in *RelatedProject → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.project_tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project_tags: prismic.GroupField<
    Simplify<RelatedProjectSliceDefaultPrimaryProjectTagsItem>
  >;

  /**
   * Project Image field in *RelatedProject → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.project_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Project Link field in *RelatedProject → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: related_project.default.primary.project_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project_link: prismic.ContentRelationshipField<"project">;
}

/**
 * Default variation for RelatedProject Slice
 *
 * - **API ID**: `default`
 * - **Description**: Highlight a related project.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RelatedProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RelatedProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RelatedProject*
 */
type RelatedProjectSliceVariation = RelatedProjectSliceDefault;

/**
 * RelatedProject Shared Slice
 *
 * - **API ID**: `related_project`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RelatedProjectSlice = prismic.SharedSlice<
  "related_project",
  RelatedProjectSliceVariation
>;

/**
 * Item in *Roadmap → Default → Primary → roadmap*
 */
export interface RoadmapSliceDefaultPrimaryRoadmapItem {
  /**
   * title field in *Roadmap → Default → Primary → roadmap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Roadmap → Default → Primary → roadmap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * media field in *Roadmap → Default → Primary → roadmap*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *Roadmap → Default → Primary*
 */
export interface RoadmapSliceDefaultPrimary {
  /**
   * Title field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitel field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.subtitel
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitel: prismic.RichTextField;

  /**
   * roadmap field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.roadmap[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  roadmap: prismic.GroupField<Simplify<RoadmapSliceDefaultPrimaryRoadmapItem>>;

  /**
   * background cta field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.background_cta
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_cta: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * cta link field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * cta label field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * cta title field in *Roadmap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField;
}

/**
 * Default variation for Roadmap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoadmapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoadmapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Roadmap*
 */
type RoadmapSliceVariation = RoadmapSliceDefault;

/**
 * Roadmap Shared Slice
 *
 * - **API ID**: `roadmap`
 * - **Description**: Roadmap
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoadmapSlice = prismic.SharedSlice<
  "roadmap",
  RoadmapSliceVariation
>;

/**
 * Item in *ServiceFit → Default → Primary → For You Items*
 */
export interface ServiceFitSliceDefaultPrimaryForYouItemsItem {
  /**
   * Icon field in *ServiceFit → Default → Primary → For You Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.for_you_items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Text field in *ServiceFit → Default → Primary → For You Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.for_you_items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *ServiceFit → Default → Primary → Not For You Items*
 */
export interface ServiceFitSliceDefaultPrimaryNotForYouItemsItem {
  /**
   * Text field in *ServiceFit → Default → Primary → Not For You Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.not_for_you_items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceFit → Default → Primary*
 */
export interface ServiceFitSliceDefaultPrimary {
  /**
   * Heading field in *ServiceFit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * For You Heading field in *ServiceFit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.for_you_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  for_you_heading: prismic.KeyTextField;

  /**
   * Not For You Heading field in *ServiceFit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.not_for_you_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  not_for_you_heading: prismic.KeyTextField;

  /**
   * Not For You Intro field in *ServiceFit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.not_for_you_intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  not_for_you_intro: prismic.KeyTextField;

  /**
   * For You Items field in *ServiceFit → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.for_you_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  for_you_items: prismic.GroupField<
    Simplify<ServiceFitSliceDefaultPrimaryForYouItemsItem>
  >;

  /**
   * Not For You Items field in *ServiceFit → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fit.default.primary.not_for_you_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  not_for_you_items: prismic.GroupField<
    Simplify<ServiceFitSliceDefaultPrimaryNotForYouItemsItem>
  >;
}

/**
 * Default variation for ServiceFit Slice
 *
 * - **API ID**: `default`
 * - **Description**: Why this service is for you vs not for you.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceFitSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceFitSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceFit*
 */
type ServiceFitSliceVariation = ServiceFitSliceDefault;

/**
 * ServiceFit Shared Slice
 *
 * - **API ID**: `service_fit`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceFitSlice = prismic.SharedSlice<
  "service_fit",
  ServiceFitSliceVariation
>;

/**
 * Item in *ServiceHero → Default → Primary → Tags*
 */
export interface ServiceHeroSliceDefaultPrimaryTagsItem {
  /**
   * Tag field in *ServiceHero → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceHero → Default → Primary*
 */
export interface ServiceHeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Description field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Tags field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<ServiceHeroSliceDefaultPrimaryTagsItem>>;

  /**
   * Background Image field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Video field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: service_hero.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ServiceHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Service hero with background media, title, tags, and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceHero*
 */
type ServiceHeroSliceVariation = ServiceHeroSliceDefault;

/**
 * ServiceHero Shared Slice
 *
 * - **API ID**: `service_hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHeroSlice = prismic.SharedSlice<
  "service_hero",
  ServiceHeroSliceVariation
>;

/**
 * Primary content in *ServiceHighlight → Default → Primary*
 */
export interface ServiceHighlightSliceDefaultPrimary {
  /**
   * Heading field in *ServiceHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_highlight.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ServiceHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_highlight.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Label field in *ServiceHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_highlight.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *ServiceHighlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_highlight.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *ServiceHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_highlight.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ServiceHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Highlight block with heading, description, CTA, and image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceHighlight*
 */
type ServiceHighlightSliceVariation = ServiceHighlightSliceDefault;

/**
 * ServiceHighlight Shared Slice
 *
 * - **API ID**: `service_highlight`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceHighlightSlice = prismic.SharedSlice<
  "service_highlight",
  ServiceHighlightSliceVariation
>;

/**
 * Item in *ServiceProcess → Default → Primary → Steps*
 */
export interface ServiceProcessSliceDefaultPrimaryStepsItem {
  /**
   * Title field in *ServiceProcess → Default → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.default.primary.steps[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ServiceProcess → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.default.primary.steps[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ServiceProcess → Default → Primary*
 */
export interface ServiceProcessSliceDefaultPrimary {
  /**
   * Heading field in *ServiceProcess → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Steps field in *ServiceProcess → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<
    Simplify<ServiceProcessSliceDefaultPrimaryStepsItem>
  >;
}

/**
 * Default variation for ServiceProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: Step-by-step process for the service.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceProcessSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceProcess*
 */
type ServiceProcessSliceVariation = ServiceProcessSliceDefault;

/**
 * ServiceProcess Shared Slice
 *
 * - **API ID**: `service_process`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceProcessSlice = prismic.SharedSlice<
  "service_process",
  ServiceProcessSliceVariation
>;

/**
 * Item in *Services → Default → Primary → Services*
 */
export interface ServicesSliceDefaultPrimaryServicesItem {
  /**
   * Hover image field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].hover_image
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  hover_image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Service description field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  service_description: prismic.RichTextField;

  /**
   * Link field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Services field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<
    Simplify<ServicesSliceDefaultPrimaryServicesItem>
  >;

  /**
   * Title field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryPhotosItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AboutWithImagesGridSlice,
      AboutWithImagesGridSliceDefaultPrimaryCardsItem,
      AboutWithImagesGridSliceDefaultPrimary,
      AboutWithImagesGridSliceVariation,
      AboutWithImagesGridSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimaryContactOptionsItem,
      ContactFormSliceDefaultPrimaryInterestServicesItem,
      ContactFormSliceDefaultPrimaryBudgetOptionsItem,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FaqWithCtaSlice,
      FaqWithCtaSliceDefaultPrimaryFaqsItem,
      FaqWithCtaSliceDefaultPrimary,
      FaqWithCtaSliceVariation,
      FaqWithCtaSliceDefault,
      FooterCtaNavigationBrandingSlice,
      FooterCtaNavigationBrandingSliceDefaultPrimaryPageNavLinksItem,
      FooterCtaNavigationBrandingSliceDefaultPrimary,
      FooterCtaNavigationBrandingSliceVariation,
      FooterCtaNavigationBrandingSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryTitleActionItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProjectCtaSlice,
      ProjectCtaSliceDefaultPrimary,
      ProjectCtaSliceVariation,
      ProjectCtaSliceDefault,
      ProjectDetailHeroSlice,
      ProjectDetailHeroSliceDefaultPrimaryTagsItem,
      ProjectDetailHeroSliceDefaultPrimary,
      ProjectDetailHeroSliceVariation,
      ProjectDetailHeroSliceDefault,
      ProjectDoubleColumnTextSlice,
      ProjectDoubleColumnTextSliceDefaultPrimaryDetailsItem,
      ProjectDoubleColumnTextSliceDefaultPrimary,
      ProjectDoubleColumnTextSliceVariation,
      ProjectDoubleColumnTextSliceDefault,
      ProjectHeroSlice,
      ProjectHeroSliceDefaultPrimaryProjectTagsItem,
      ProjectHeroSliceDefaultPrimary,
      ProjectHeroSliceVariation,
      ProjectHeroSliceDefault,
      ProjectMediaGridSlice,
      ProjectMediaGridSliceDefaultPrimaryItemsItem,
      ProjectMediaGridSliceDefaultPrimary,
      ProjectMediaGridSliceVariation,
      ProjectMediaGridSliceDefault,
      ProjectSingleMediaSlice,
      ProjectSingleMediaSliceDefaultPrimary,
      ProjectSingleMediaSliceVariation,
      ProjectSingleMediaSliceDefault,
      ProjectStatsSlice,
      ProjectStatsSliceDefaultPrimaryStatsItem,
      ProjectStatsSliceDefaultPrimary,
      ProjectStatsSliceVariation,
      ProjectStatsSliceDefault,
      ProjectTestimonialSlice,
      ProjectTestimonialSliceDefaultPrimary,
      ProjectTestimonialSliceVariation,
      ProjectTestimonialSliceDefault,
      ProjectTitleParagraphSlice,
      ProjectTitleParagraphSliceDefaultPrimary,
      ProjectTitleParagraphSliceVariation,
      ProjectTitleParagraphSliceDefault,
      RelatedProjectSlice,
      RelatedProjectSliceDefaultPrimaryProjectTagsItem,
      RelatedProjectSliceDefaultPrimary,
      RelatedProjectSliceVariation,
      RelatedProjectSliceDefault,
      RoadmapSlice,
      RoadmapSliceDefaultPrimaryRoadmapItem,
      RoadmapSliceDefaultPrimary,
      RoadmapSliceVariation,
      RoadmapSliceDefault,
      ServiceFitSlice,
      ServiceFitSliceDefaultPrimaryForYouItemsItem,
      ServiceFitSliceDefaultPrimaryNotForYouItemsItem,
      ServiceFitSliceDefaultPrimary,
      ServiceFitSliceVariation,
      ServiceFitSliceDefault,
      ServiceHeroSlice,
      ServiceHeroSliceDefaultPrimaryTagsItem,
      ServiceHeroSliceDefaultPrimary,
      ServiceHeroSliceVariation,
      ServiceHeroSliceDefault,
      ServiceHighlightSlice,
      ServiceHighlightSliceDefaultPrimary,
      ServiceHighlightSliceVariation,
      ServiceHighlightSliceDefault,
      ServiceProcessSlice,
      ServiceProcessSliceDefaultPrimaryStepsItem,
      ServiceProcessSliceDefaultPrimary,
      ServiceProcessSliceVariation,
      ServiceProcessSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryServicesItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
    };
  }
}
