// Code generated by Slice Machine. DO NOT EDIT.

import AboutSection from './AboutSection';
import BehindTheVine from './BehindTheVine';
import FeaturedSection from './FeaturedSection';
import IntroSection from './IntroSection';
import RoadmapSection from './RoadmapSection';
import ServicesSection from './ServicesSection';
import TestimonialSection from './TestimonialSection';
import ToolkitSection from './ToolkitSection';

export {
	AboutSection,
	BehindTheVine,
	FeaturedSection,
	IntroSection,
	RoadmapSection,
	ServicesSection,
	TestimonialSection,
	ToolkitSection,
};

export const components = {
	about_section: AboutSection,
	behind_the_vine: BehindTheVine,
	featured_section: FeaturedSection,
	intro_section: IntroSection,
	roadmap_section: RoadmapSection,
	services_section: ServicesSection,
	testimonial_section: TestimonialSection,
	toolkit_section: ToolkitSection,
};
