// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  about_with_images_grid: dynamic(() => import("./AboutWithImagesGrid")),
  contact_form: dynamic(() => import("./ContactForm")),
  faq_with_cta: dynamic(() => import("./FaqWithCta")),
  footer_cta_navigation_branding: dynamic(
    () => import("./FooterCtaNavigationBranding"),
  ),
  hero: dynamic(() => import("./Hero")),
  project_cta: dynamic(() => import("./ProjectCTA")),
  project_detail_hero: dynamic(() => import("./ProjectDetailHero")),
  project_double_column_text: dynamic(() => import("./ProjectDoubleColumnText")),
  project_media_grid: dynamic(() => import("./ProjectMediaGrid")),
  project_single_media: dynamic(() => import("./ProjectSingleMedia")),
  project_hero: dynamic(() => import("./ProjectHero")),
  project_stats: dynamic(() => import("./ProjectStats")),
  project_testimonial: dynamic(() => import("./ProjectTestimonial")),
  project_title_paragraph: dynamic(() => import("./ProjectTitleParagraph")),
  roadmap: dynamic(() => import("./Roadmap")),
  services: dynamic(() => import("./Services")),
};
