import Head from "next/head"
import { SliceZone } from "@prismicio/react"
import { createClient } from "../../prismicio"
import { components } from "../../slices"
import { useRef } from "react"
import { useIsomorphicLayoutEffect } from "@/helpers/useIsomorphicLayoutEffect"

export default function Home({ page, navigation, settings }) {
	const scrollRef = useRef()

	return (
		<>
			<Head>
				<title>© BAYVINE DIGITAL AGENCY</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<main className="" ref={scrollRef}>
				<SliceZone slices={page.data.slices} components={components} />
			</main>
		</>
	)
}

export async function getStaticProps({ previewData }) {
	const client = createClient({ previewData })

	const page = await client.getSingle("homepage")

	return {
		props: {
			page,
		},
	}
}
